# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('level', models.IntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('steam_id', models.TextField()),
                ('conan_id', models.TextField()),
                ('last_online', models.DateTimeField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('last_killed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('public_secret', models.UUIDField()),
                ('private_secret', models.UUIDField()),
            ],
        ),
    ]
