# Generated by Django 2.0.6 on 2018-06-19 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('level', models.IntegerField()),
                ('is_online', models.BooleanField()),
                ('steam_id', models.TextField()),
                ('conan_id', models.TextField()),
                ('conan_clan_id', models.TextField(null=True)),
                ('last_online', models.DateTimeField(null=True)),
                ('last_killed_by', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('z', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='api.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('conan_id', models.TextField()),
                ('conan_owner_id', models.TextField()),
                ('motd', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='api.Character')),
            ],
        ),
        migrations.CreateModel(
            name='GinfoCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ginfo_marker_uid', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ginfo_character', related_query_name='ginfo_character', to='api.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ip_address', models.TextField(default='')),
                ('version', models.TextField(null=True)),
                ('query_port', models.TextField(null=True)),
                ('max_players', models.IntegerField(null=True)),
                ('tick_rate', models.IntegerField(null=True)),
                ('private_secret', models.UUIDField()),
                ('last_sync', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerSyncData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Server')),
            ],
        ),
        migrations.AddField(
            model_name='clan',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clans', to='api.Server'),
        ),
        migrations.AddField(
            model_name='character',
            name='clan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='api.Clan'),
        ),
        migrations.AddField(
            model_name='character',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='characters', to='api.Server'),
        ),
    ]
