# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 01:54
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('level', models.IntegerField()),
                ('is_online', models.BooleanField()),
                ('steam_id', models.TextField()),
                ('conan_id', models.TextField()),
                ('last_online', models.DateTimeField(null=True)),
                ('last_killed_by', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('public_secret', models.UUIDField()),
                ('private_secret', models.UUIDField()),
                ('last_sync', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server'),
        ),
    ]
