# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-28 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial_squash'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='rcon_host',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='rcon_password',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='rcon_port',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='sync_rcon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
