# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_test_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='public_secret',
        ),
    ]
