# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170620_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Server'),
            preserve_default=False,
        ),
    ]
