# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ginfo_marker_uid',
            field=models.TextField(blank=True),
        ),
    ]
