# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 04:52
from __future__ import unicode_literals

from django.db import migrations
from datetime import datetime
from django.utils import timezone
import uuid


def add_data(apps, schema_editor):
	Server = apps.get_model('api', 'Server')
	Character = apps.get_model('api', 'Character')

	server =  Server.objects.create(
		name='Test Server',
		public_secret=uuid.uuid1(),
		private_secret=uuid.uuid1())

	char1 = Character.objects.create(
		name='NullSoldier',
		level=5,
		is_online=False,
		steam_id=76561197963906761,
		conan_id=1,
		last_online=timezone.now(),
		last_killed_by=None,
		server=server,
		x=0,
		y=0,
		z=0)

	char2 = Character.objects.create(
		name='Immotal',
		level=8,
		is_online=True,
		steam_id=76561197984850480,
		conan_id=2,
		last_online=timezone.now(),
		last_killed_by_id=char1.id,
		server=server,
		x=0,
		y=0,
		z=0)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_character_server'),
    ]

    operations = [
    	migrations.RunPython(add_data)
    ]
