# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-15 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_server_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='version',
            field=models.TextField(null=True),
        ),
    ]
