# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-17 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_server_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='z',
            field=models.FloatField(null=True),
        ),
    ]
