# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ginfocharacter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('conan_id', models.TextField()),
                ('owner_id', models.TextField()),
                ('motd', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server')),
            ],
        ),
    ]
